### ISSUE TITLE
Clarification: Cache Property on Collections

### ISSUE THREAD

**Issue by GaryGSC** [byu-oit/UAPI-Specification#12]
When returning a cached collection, is it sufficient to add a cache property to the [metadata of the collection](https://github.com/byu-oit/UAPI-Specification/blob/master/University%20API%20Specification.md#332-collection-metadata) alone, or do I also need to add a cache property to the [metadata of each individual item](https://github.com/byu-oit/UAPI-Specification/blob/master/University%20API%20Specification.md#322-metadata)?

**Comment by brentmoore** [comment]
The preference would be to add it to each individual item. The reason is that we want the item to be consistent regardless of if it came from a collection or was queried on its own.
