### ISSUE TITLE
Define behavior when no field_set is successful

### ISSUE THREAD

**Issue by GaryGSC** [byu-oit/UAPI-Specification#23]
The wording in [12.5](https://github.com/byu-oit/UAPI-Specification/blob/develop/University%20API%20Specification.md#125-partial-error-response) is ambiguous about behavior when no field_set is successful (e.g., when I get a 403 and a 500).

Say I perform a GET on `https://api.byu.edu/byuapi/persons/123456789?field_sets=government_records,addresses`, but I get a `403 Unauthorized` for government_records and a `500 Internal Server Error` for addresses. Is the HTTP status code for the entire request `200 Success`?

**Comment by brentmoore** [comment]
Addressed by changing the first bullet point to be 'The HTTP status code for the entire request is `200 Success`. '
