### ISSUE TITLE
Clarification: Restricted flag in metadata for resources that do not deal with individuals

### ISSUE THREAD

**Issue by GaryGSC** [byu-oit/UAPI-Specification#24]
[Section 3.2.2](https://github.com/byu-oit/UAPI-Specification/blob/develop/University%20API%20Specification.md#322-metadata) says the `restricted` flag is "required if the resource deals with an individual", which I take to imply that if the resource doesn't deal with an individual, the flag is not required.

However, [section 11.6](https://github.com/byu-oit/UAPI-Specification/blob/develop/University%20API%20Specification.md#116-restricted-resources) states "resources that do not deal with individuals should include the metadata element [referring to the `restricted` flag] with the value always set to false."

For resources that do not deal with individuals, is the `restricted` flag required?

**Comment by brentmoore** [comment]
Handled by changing the 'should' to 'may' in 11.6.
