### ISSUE TITLE
Response body for resource creation and updates

### ISSUE THREAD

**Issue by ThatJoeMoore** [byu-oit/UAPI-Specification#31]
Section [10.2](https://github.com/byu-oit/UAPI-Specification/blob/develop/University%20API%20Specification.md#102-post) specifies the response code for a successful create, and that it sends a `Location` header, but doesn't say anything about the response body.

Section [10.1](https://github.com/byu-oit/UAPI-Specification/blob/develop/University%20API%20Specification.md#101-put) doesn't say anything about the response for an update.  We should probably either say that it's `204 No Content` or `200 OK`, and if we decide that it should be 200, the response should be consistent with the 201 response from a create.

I see three reasonable responses:

- No body. Less than desirable, especially since the definition for `HTTP 201` requires a response entity.
- Metadata-only body. Just include response metadata and HATEOAS links for the created or updated resource. This requires the caller to make a GET to see what they created.
- Body with properties. For POSTs and PUTs to a top-level resource, include the properties and links of the `basic` fieldset. For subresources, include the properties and links of the subresource.

I can also see an argument to be made that the response body for a request that creates or modifies a top-level resource should be the same as a GET on that resource with no fieldsets requested. This may be a bit harder to generate on the server, but it makes it substitutable for a normal GET request.

Personally, I lean towards the third option, sending back the stuff that was created or modified.  Often, a client will need to get the resource it just created, as there are often system-generated things (like identifiers) that it needs to display.

**Comment by brentmoore** [comment]
Added the following to the PUT and POST resource creation (and something similar to the PUT update) - "When a new resource is created an HTTP Status Code of `201` should be returned along with the `Location` HTTP header containing the URL for the new resource. The body of the response should contain either the `basic` field\_set or the sub-resource just created."
