### ISSUE TITLE
Clarification: Some Minor Inconsistencies

### ISSUE THREAD

**Issue by GaryGSC** [byu-oit/UAPI-Specification#5]
I see a few inconsistencies:

- `default_field_sets` vs `field_sets_default` - I think `default_field_sets` is currently more common.
- `application/json-extended` vs `application/json+extended` - I don't know of anything using either, but I see you've mentioned both of these as mime-types. I assume they're supposed to be the same thing.
- `__current` vs `__info` - The docs for links seem to imply that we use `__current` when referring to a page and `__info` when referring to a single item. The examples seem to use `__info` for pages, which makes `__current` look like a typo.

**Comment by brentmoore** [comment]
`field_sets_default` is used by the persons API which is the one I've used for reference. If it is the other way in the others we can switch it. 

The mime-type is being changed to `application/json-uapi` - see issue #10. 

Should be `__info` I believe. I'll fix that.

**Comment by brentmoore** [comment]
Actually, `__info` should give you the collection - `__current` should give you back this page in the collection.
