### ISSUE TITLE
Description and Long Description Lengths

### ISSUE THREAD

**Issue by jvisker** [byu-oit/UAPI-Specification#6]
Do we have any guidelines on how long "Description" and "Long Description" should be? It seems like it would be useful from a UI perspective that the description will be in a certain size range.

**Comment by brentmoore** [comment]
Good Question. In the old systems descriptions were usually 30 and long descriptions 256 but that was because of technology limitations. Any thoughts as to what they should be now?

**Comment by jvisker** [comment]
I think we probably ought to suggest some maximum sizes for those two fields and display_label. Unless we are willing to to add some more meta information that allows the api writers to specify the maximum length of the descriptions and labels.

**Comment by brentmoore** [comment]
I think we'll start with 30 for the description and display_label. 256 for long description. The same for the values in the meta responses as well.
